In [45]:
import pandas as pd


In [46]:
import numpy as np


In [2]:
pd.__version__

'3.0.6'

In [24]:
df=pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [7]:
df.shape[0]

10000

In [8]:
len(df)

10000

In [9]:
df['fuel_type'].nunique()

3

In [10]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [11]:
df.isnull().any().sum()

np.int64(2)

In [12]:
df.isna().sum().gt(0).sum()

np.int64(2)

In [14]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [28]:
df['horsepower'].median()

np.float64(254.0)

In [22]:
df['horsepower'].mode()[0]

np.float64(252.0)

In [26]:
most_frequent = df['horsepower'].mode()[0]
df_edit = df.copy()
df_edit['horsepower'] = df_edit['horsepower'].fillna(most_frequent)

In [29]:
df_edit['horsepower'].median()

np.float64(252.0)

In [30]:
df_edit['horsepower'].median()

np.float64(252.0)

In [33]:
#Select all the cars from Asia
asia = df[df['origin'] == 'Asia']

In [40]:
#Select only columns vehicle_weight and model_year
#Select the first 7 values
#Get the underlying NumPy array. Let's call it X.
X = asia[['vehicle_weight', 'model_year']].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [41]:
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [47]:
#Invert XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [48]:
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [50]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [51]:
#What's the sum of all the elements of the result?
w.sum()

np.float64(0.36919696904925486)